name: ZIKV_DMS_NS5_EvansLab
channels:
  - bioconda
  - conda-forge
  - schrodinger
dependencies:
  - imagemagick
  - jupyterlab
  - mamba
  - nbdime
  - nodejs
  - pandas=0.25.3
  - pip
  - python=3.8
  - pip:
    - dms_tools2==2.6.10
    - dmslogo==0.6.2
    - snakemake==6.5.2
    - numpy<1.20
    - altair
    - vega_datasets
    - dms_variants
    - statsmodels==0.13.2
