name: ZIKV_DMS_NS5_EvansLab
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
  - schrodinger
dependencies:
  - imagemagick
  - jupyterlab
  - mamba
  - nbdime
  - nodejs
  - pip
  - python=3.8
  - pip:
    - dms_tools2==2.6.9
    - dmslogo==0.6.2
    - snakemake==6.5.2
