name: ZIKV_DMS
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
  - schrodinger
dependencies:
  - imagemagick
  - jupyterlab
  - nbdime
  - nodejs
  - pip
  - python=3.8
  - pip:
    - dms_tools2
    - dmslogo
